### ISSUE TITLE
Initial Release - Development

### ISSUE THREAD

**Issue by uk-bolly** [ansible-lockdown/RHEL9-CIS#1]
Hi All

We are aware that RHEL9 is currently in devel, but in order to preempt what maybe coming and to start with a consistent base, we have released a role for the predicted RHEL9 based upon RHEL8 CIS currently.

This does have a few changes ([Changelog.md](https://github.com/ansible-lockdown/RHEL9-CIS/Changelog.md)) to the RHEL8 branch regarding changes to sysctl and auditd controls. We have moved to a template model rather than individual commands.
This is provides quite a speed improvement. The benchmark control now runs debug message with a notify handler and add the controls at end during post.yml. Still using all the variables as set in your files.
It does change the file thats added if the variable is true it will change the file even if not used via tag.
maybe we can add a sysctl_apply: true variable?

Before we make further changes please let us know how this works?

Thanks

uk-bolly

**Comment by MPG-helper** [comment]
What do with think to check_mode?

**Comment by MPG-helper** [comment]
How about adding docs?
e.g. readthedocs?

**Comment by georgenalen** [comment]
test

**Comment by uk-bolly** [comment]
testing again

**Comment by uk-bolly** [comment]
Chat being moved to discord channel
