### ISSUE TITLE
CIS 5.6.x -- USERGROUPS_ENAB no

### ISSUE THREAD

**Issue by bdwyertech** [ansible-lockdown/RHEL9-CIS#101]
What is the point of setting `USERGROUPS_ENAB no` for this rule?  Is this a typo?  Just curious.  I'm overriding this control and leaving it to yes.

https://github.com/ansible-lockdown/RHEL9-CIS/blob/9fa57a2b41bfefb0f46eb0795333e71480367642/tasks/section_5/cis_5.6.x.yml#L95-L99

**Comment by uk-bolly** [comment]
hi @bdwyertech 

Thanks for raising the issue. I believe that CIS documentation is trying to ensure that UMASK is only set in one manner.  By setting on a user profile level and not in multiple places by allow usergroups_enab. Also removing the risks that ciould be associated with have the default yes.

Excert from the documentation.
```
Setting USERGROUPS_ENAB to yes in /etc/login.defs (default):
- will enable setting of the umask group bits to be the same as owner bits. (examples: 022 -> 002, 077 -> 007) for non-root users, if the
uid is the same as gid, and username is the same as the <primary group name>
- userdel will remove the user's group if it contains no more members, and useradd will create by default a group with the name of the user```

I hope that answers your questions.

uk-bolly

**Comment by bdwyertech** [comment]
Thanks for the explanation! I stumbled into this as many things broke on my end due to useradd not creating a corresponding group.  I will simply omit this rule.
