### ISSUE TITLE
Question: Incorrect condition for cis_1.3..3 

### ISSUE THREAD

**Issue by p3ll1n0r3** [ansible-lockdown/RHEL9-CIS#111]
**Question**

tasks/section_1/cis_1.3.x.yml

at task: 
- name: "1.3.3 | Ensure cryptographic mechanisms are used to protect the integrity of audit tools"

has a condition "when"

  when:
      - rhel9cis_rule_1_3_2

Should it not be:

  when:
      - rhel9cis_rule_1_3_3

**Environment (please complete the following information):**

- Ansible Version: 2.14.2
- Host Python Version: Python 3.11.2
- Ansible Server Python Version: Python 3.11.2

**Comment by uk-bolly** [comment]
hi @p3ll1n0r3 

Thank you for taking ths time to raise this issue, this is now in devel
https://github.com/ansible-lockdown/RHEL9-CIS/pull/151

We will be cutting a new release to main in the coming weeks.

many thanks

uk-bolly
