### ISSUE TITLE
Document variables in defaults/main.yml

### ISSUE THREAD

**Issue by brisky** [ansible-lockdown/RHEL9-CIS#123]
## Feature Request or Enhancement

- Feature [variables in main]
- Enhancement [Document most variables with it's purpose.]

**Summary of Request**
Add comments on all variables, so anyone can understand the meaning and the options on each one.

**Describe Alternatives You've Considered**
Maybe create additional documentation with more detailed info.

**Suggested Code**
Add inline comments on the variables files.
Starting with main.yml.

**Comment by uk-bolly** [comment]
closed as PR closed
