### ISSUE TITLE
Audit log files must have mode 0640 or less permissive ?

### ISSUE THREAD

**Issue by paul-grozav** [ansible-lockdown/RHEL9-CIS#126]
## Feature Request or Enhancement

- Feature [x]
- Enhancement [x]

**Summary of Request**
[CIS 4.2.3](https://github.com/ansible-lockdown/RHEL9-CIS/blob/8405e67db24ae0c2389ba5ba7312c02b687b3494/tasks/section_4/cis_4.2.3.yml#L15) sets more open permissions for `/var/log/audit/audit.log`. The auditd system only asks for mode 600(a-rwx, u+rw) (`-rw-------`), but CIS 4.2.3 adds `g+r` making it 640 or `-rw-r-----`.
```json
...
        {
          "_ansible_item_label": "/var/log/audit/audit.log",
          "_ansible_no_log": null,
          "ansible_loop_var": "item",
          "changed": true,
          "diff": {
            "after": {
              "mode": "0640",
              "path": "/var/log/audit/audit.log"
            },
            "before": {
              "mode": "0600",
              "path": "/var/log/audit/audit.log"
            }
          },
          "failed": false,
...
```
Though not clearly stated in the CIS guideline, it seems that other guidelines like this one: https://www.stigviewer.com/stig/red_hat_enterprise_linux_6/2020-09-03/finding/V-218084 says that "*Audit log files must have mode 0640 **or less permissive**.*"

**Describe Alternatives You've Considered**
Apply mode 640 (only) when the current/existing mode > 640 .

**Suggested Code**
Please provide any code you have in mind to fulfill the request

I'm not sure how we can specify a `when` filter, that applies per `item` instead of applying it at the entire task level.

**Comment by rjacobs1990** [comment]
https://github.com/ansible-lockdown/RHEL9-CIS/pull/175
i think this PR will solve this issue also.
