### ISSUE TITLE
Variables used for audit were not defined

### ISSUE THREAD

**Issue by ipruteanu-sie** [ansible-lockdown/RHEL9-CIS#130]
**Describe the Issue**
I suppose values: `copy` vs `archive` for `audit_content` variable are pretty much the same, the only difference is if we'll handle the specified filepath via `ansible.builtin.unarchive:` or `ansible.builtin.copy`. However, some non-defined vars within the role are used for the `Copy to audit content files to server` task.

**Expected Behavior**
This task for copy in `pre_remediation_audit.yml` file should use `audit_conf_copy` & `audit_conf_dir`
- name: Pre Audit Setup | Copy to audit content files to server
  when:
      - audit_content == 'copy'
  ansible.builtin.copy:
      src: "{{ audit_conf_copy }}"
      dest: "{{ audit_conf_dir }}"
      mode: preserve

**Actual Behavior**
The above task for copy in `pre_remediation_audit.yml` uses potentially wrong variables: `audit_local_copy` and `audit_conf_dest `:
- name: Pre Audit Setup | Copy to audit content files to server
  when:
      - audit_content == 'copy'
  ansible.builtin.copy:
      src: "{{ audit_local_copy }}"
      dest: "{{ audit_conf_dest }}"
      mode: preserve

**Control(s) Affected**
N/A, just the `Copy to audit content files to server` pre-remediation task.
**Environment (please complete the following information):**

- branch being used: [e.g. devel]

**Possible Solution**
A PR will be provided immediately.

**Comment by uk-bolly** [comment]
hi @ipruteanu-sie 

This Issue has been merged to devel and into main branch. I will therefore close this issue.
Please feel free to reopen if you feel its not as expected.

Many thanks again for your time

uk-bolly
