### ISSUE TITLE
Defined var for timeout not used

### ISSUE THREAD

**Issue by ipruteanu-sie** [ansible-lockdown/RHEL9-CIS#132]
**Describe the Issue**
In [`defaults/main.yml` file](https://github.com/ansible-lockdown/RHEL9-CIS/blob/8405e67db24ae0c2389ba5ba7312c02b687b3494/defaults/main.yml#L92), there's this default definition:
```
audit_cmd_timeout: 120000
```
However, this is not used. Is this the intended way ?

**Expected Behavior**
A reference should be made towards `audit_cmd_timeout` variable, most probably in [`ansible_vars_goss.yml.j2` file](https://github.com/ansible-lockdown/RHEL9-CIS/blob/8405e67db24ae0c2389ba5ba7312c02b687b3494/templates/ansible_vars_goss.yml.j2#L13):
```
timeout_ms: {{ audit_cmd_timeout }}
# instead of
# timeout_ms: 60000
```

**Actual Behavior**
[`ansible_vars_goss.yml.j2` file](https://github.com/ansible-lockdown/RHEL9-CIS/blob/8405e67db24ae0c2389ba5ba7312c02b687b3494/templates/ansible_vars_goss.yml.j2#L13) contains a new value, making the default value never used:
```
timeout_ms: 60000
```

**Control(s) Affected**
N/A, Goss

**Environment (please complete the following information):**

- branch being used: [e.g. devel]
**Possible Solution**
Added a PR.

**Comment by uk-bolly** [comment]
hi @ipruteanu-sie 

This Issue has been merged to devel and into main branch. I will therefore close this issue.
Please feel free to reopen if you feel its not as expected.

Many thanks again for your time

uk-bolly
