### ISSUE TITLE
Variables not used at all within role

### ISSUE THREAD

**Issue by ipruteanu-sie** [ansible-lockdown/RHEL9-CIS#134]
**Question**
These vars in 'defaults/main.yml' file are not used within role:
- [x]  **rhel9cis_allow_autofs: false** (_NOTE: Setting to 'false' this variable will disable the automounting service(autofs), used for automatically mounting the filesystem and remote-shares._)
        -  for example, in ubuntu22 role it was used in [templates/ansible_vars_goss.yml.j2](https://github.com/siemens/UBUNTU22-CIS/blob/9d678015d62fd573c26ca3cf5dcfe8186d637194/templates/ansible_vars_goss.yml.j2#L375)
        - and afterwards in [`tasks/section_1/cis_1.1.9.yml || cis_1.1.x.yml`](https://github.com/siemens/UBUNTU22-CIS/blob/9d678015d62fd573c26ca3cf5dcfe8186d637194/tasks/section_1/cis_1.1.9.yml#L3)

- [x] **rhel9cis_rh_sub_user & rhel9cis_rh_sub_password**(_NOTE: Providing the username and password for "Red Hat Subscription Manager" connection._)
     	- in RHEL8, they were used for [configuring the RH Subscription Manager](https://github.com/ansible-lockdown/RHEL8-CIS/blob/c1ef93526b7828f20018d2945efe962e09144cff/tasks/section_1/cis_1.2.x.yml#L6)

- [x] **rhel9cis_rhnsd_required**(_NOTE: If var "rhel7cis_rhnsd_required" would be set to false, the rhnsd daemon, which periodically connects to Red Hat Network Satellite to check for updates and notifications, will be stopped._)
        -  in RHEL7, it was used in [tasks/section_1/cis_1.2.x.yml](https://github.com/ansible-lockdown/RHEL7-CIS/blob/d7f643a053b2f193d2f00ae7b6dc07e3b214e883/tasks/section_1/cis_1.2.x.yml#L83)

- [x] **rhel9cis_bootloader_password**()
       - Such a variable seem to be used in:
		- other `*-CIS-Audit` repos, in 'vars/CIS.yml' file
		- other `*-CIS` repos, in ['templates/ansible_vars_goss.yml.j2'](https://github.com/ansible-lockdown/UBUNTU22-CIS/blob/fa365a36ca48f58237d87d5f6d90c380cb7de2ae/templates/ansible_vars_goss.yml.j2#L381) files for loading the hashed password:
```
				# 1.5.1 Bootloader password
				ubtu22cis_bootloader_password: {{ ubtu22cis_bootloader_password_hash }}
```
but in current repository [NO other reference exists](https://github.com/search?q=repo%3Aansible-lockdown%2FRHEL9-CIS%20_bootloader_password%3A&type=code) for it.

- [x] **cis_firewalld_ports** (not used and documented as [an example](https://github.com/search?q=org%3Aansible-lockdown+cis_firewalld_ports&type=code) in RHEL9 & AL2023 )
```
# These settings are added to demonstrate how this update can be done (eventually will require a new control)
rhel9cis_firewalld_ports:
    - number: 80
      protocol: tcp
```

- [x] **rhel9cis_passwd_label** - 6.2.10(`Ensure local interactive user home directories exist`):
    -  Used in rhel8 as a label for `loop_control`, when [iterating over passwd lines](https://github.com/ansible-lockdown/RHEL8-CIS/blob/c1ef93526b7828f20018d2945efe962e09144cff/tasks/section_6/cis_6.2.x.yml#L306).
    -  (Not used in rhel9, **despite defined**): rule [6.2.10 uses only `{{ item.id }}`](https://github.com/ansible-lockdown/RHEL9-CIS/blob/8405e67db24ae0c2389ba5ba7312c02b687b3494/tasks/section_6/cis_6.2.x.yml#L283) as a label for loop_control.

Please let me know about your thoughts on this variable definition without actual usage.

**Comment by uk-bolly** [comment]
hi @ipruteanu-sie 

Thank you for taking the time and providing the feedback for this issue. I can agree, some of the values do need validated. More than happy to remove unused of variables that are no longer valid.
Will looking to add this into an upcoming PR and release.

Many thanks

uk-bolly

**Comment by uk-bolly** [comment]
hi @ipruteanu-sie 

This Issue has been merged to devel and into main branch. I will therefore close this issue.
Please feel free to reopen if you feel its not as expected.

Many thanks again for your time

uk-bolly
