### ISSUE TITLE
Correct conditional for: `3.4.2.5 | AUDIT | Ensure firewalld drops unnecessary services and ports` rule

### ISSUE THREAD

**Issue by ipruteanu-sie** [ansible-lockdown/RHEL9-CIS#139]
**Describe the Issue**
missing conditional for firewalld specific task:
```
"3.4.2.5 | AUDIT | Ensure firewalld drops unnecessary services and ports"
```

**Expected Behavior**
```
  when:
      - rhel9cis_rule_3_4_2_5
      - rhel9cis_firewall == "firewalld"
```
**Actual Behavior**
```
  when:
      - rhel9cis_rule_3_4_2_5
```

**Control(s) Affected**
3.4.2.5

**Environment (please complete the following information):**

- branch being used: [e.g. devel]

**Possible Solution**
PR.

**Comment by uk-bolly** [comment]
hi @ipruteanu-sie 

This Issue has been merged to devel and into main branch. I will therefore close this issue.
Please feel free to reopen if you feel its not as expected.

Many thanks again for your time

uk-bolly
