### ISSUE TITLE
a pair of tags in 5.6 are mismatching with their task

### ISSUE THREAD

**Issue by numericillustration** [ansible-lockdown/RHEL9-CIS#149]
**Describe the Issue**
task 5.6.1.1 is mistagged
task 5.6.1.5 is mistagged

**Expected Behavior**
task 5.6.1.1 is tagged as 5.6.11
task 5.6.1.5 is tagged as 5.6.1.5

**Actual Behavior**
task 5.6.1.1 is mistagged as 5.5.11
task 5.6.1.5 is mistagged as 5.5.1.5

**Control(s) Affected**
5.6.1.1
5.6.1.5

**Environment (please complete the following information):**

- branch being used: devel
- Ansible Version: core 2.12.7
- Host Python Version: 3.10.2 (v3.10.2:a58ebcc701, Jan 13 2022, 14:50:16) [Clang 13.0.0 (clang-1300.0.29.30)]

**Possible Solution**
adjust the tags to match the sections.

**Comment by uk-bolly** [comment]
hi @numericillustration 

This Issue has been merged to devel and into main branch. I will therefore close this issue.
Please feel free to reopen if you feel its not as expected.

Many thanks again for your time

uk-bolly
