### ISSUE TITLE
Var name inconsistent between `defaults/main.yml` and actual task usage

### ISSUE THREAD

**Issue by ipruteanu-sie** [ansible-lockdown/RHEL9-CIS#182]
**Describe the Issue**
`5.2.4` uses some vars, like: `allowusers, allowgroups, denyusers, denygroups`, while in `defaults/main.yml` these vars were declared with underscores:
```
allow_users, allow_groups, deny_users, deny_groups
```

**Expected Behavior**
Vars name should be the same.

**Actual Behavior**
Vars name is different, thus tasks are skipped, since the condition will never be met(value for these vars will be empty):
```
TASK [/mnt/d/code-siemens/iss_pss_gov/infosec-pss-gov/security-crafter-baseline-automations/Ansible-Lockdown/rhel9-cis : 5.2.4 | PATCH | Ensure SSH access is limited | Add line to sshd_config for allowusers] ***
skipping: [192.168.2.133] => {"changed": false, "skip_reason": "Conditional result was False"}
```

**Control(s) Affected**
5.2.4

**Environment (please complete the following information):**

- branch being used: [e.g. devel]

**Possible Solution**
PR

**Comment by uk-bolly** [comment]
hi @ipruteanu-sie 

This Issue has been merged to devel and into main branch. I will therefore close this issue.
Please feel free to reopen if you feel its not as expected.

Many thanks again for your time

uk-bolly
