### ISSUE TITLE
Extra space in regex causes gnome tools to not work

### ISSUE THREAD

**Issue by tedunder237** [ansible-lockdown/RHEL9-CIS#216]
**Describe the Issue**
An extra space in the regex is causing various gnome tools to not work properly

**Expected Behavior**
Gnome tools to work properly

**Actual Behavior**
Extra space is causing gnome tools to emit an error and not save configurations

**Control(s) Affected**
1.8.4

**Environment (please complete the following information):**

- branch being used: 1.3.1
- Ansible Version: 2.4.19
- Host Python Version: 3.9.18
- Additional Details: Rocky 9

**Possible Solution**
Change the following lines in tasks/section_1/cis_1.8.x.yml, line 92-93
Current:
```
            - { regexp: '^user-db', line: 'user-db: user' }
            - { regexp: '^system-db', line: 'system-db: local' }
```
To:
```
            - { regexp: '^user-db', line: 'user-db:user' }
            - { regexp: '^system-db', line: 'system-db:local' }
```

Tested on Rocky 9

**Comment by uk-bolly** [comment]
hi @tedunder237 

Thank you for taking the time to raise this issue, it always helps to get the details you have provided.
I am hoping to get this resolved and wityh a couple of other changes into the devel branch asap.

Many thanks

uk-bolly

**Comment by uk-bolly** [comment]
hi @tedunder237 

As you may have seen, this was released to devel and is now in the main branch and should be resolved. I will close this issue, please reopen if you still see issues.

many thanks

uk-bolly
