### ISSUE TITLE
pipeline failed when applid TASK 4.1.4.5 | PATCH | Ensure audit configuration files are 640 or more restrictive

### ISSUE THREAD

**Issue by globalpayments-shoebsyed** [ansible-lockdown/RHEL9-CIS#224]
**Describe the Issue**
We are using tag 1.1.0 earlier we were able to build with this tag however from past 2 week we are receiving an error :
TASK [rhel9-cis : 4.1.4.5 | PATCH | Ensure audit configuration files are 640 or more restrictive] ***
ok: [default] => (item=/etc/audit/audit-stop.rules)
ok: [default] => (item=/etc/audit/auditd.conf)
 ok: [default] => (item=/etc/audit/audit.rules)
failed: [default] (item=/etc/audit/plugins.d/af_unix.conf) => {"ansible_loop_var": "item", "changed": false, "item": {"atime": 1722421840.0140007, "ctime": 1719925417.7236106, "dev": 66308, "gid": 0, "gr_name": "root", "inode": 25319108, "isblk": false, "ischr": false, "isdir": false, "isfifo": false, "isgid": false, "islnk": false, "isreg": true, "issock": false, "isuid": false, "mode": "0640", "mtime": 1651663233.0, "nlink": 1, "path": "/etc/audit/plugins.d/af_unix.conf", "pw_name": "root", "rgrp": true, "roth": false, "rusr": true, "size": 358, "uid": 0, "wgrp": false, "woth": false, "wusr": true, "xgrp": false, "xoth": false, "xusr": false}, "msg": "file (/etc/audit/plugins.d/af_unix.conf) is absent, cannot continue", "path": "/etc/audit/plugins.d/af_unix.conf", "state": "absent"}

Could you please help us this to resolve, If we mark this task false what will be the issue or 

**Expected Behavior**

**Actual Behavior**
A clear and concise description of what's happening.

**Control(s) Affected**
What controls are being affected by the issue

**Environment (please complete the following information):**

- branch being used: devel
- Ansible Version: core 2.16.9
- Host Python Version: [e.g. Python 3.7.6]
- Ansible Server Python Version: [e.g. Python 3.7.6]
- Additional Details:

**Additional Notes**
Anything additional goes here

**Possible Solution**
Enter a suggested fix here

**Comment by uk-bolly** [comment]
hi @globalpayments-shoebsyed 

Thank you for taking the time to raise this issue. I have added an enhancement, to hopefully stop this from happening in future.
I will be raising the PR to get moved to devel last today.

Many thanks

uk-bolly

**Comment by uk-bolly** [comment]
hi @globalpayments-shoebsyed 

You should find this is now in the main branch and released. I will therefore close this issue off. 

many thanks

uk-bolly
