### ISSUE TITLE
4.1.4.3 fails in check mode

### ISSUE THREAD

**Issue by karlg100** [ansible-lockdown/RHEL9-CIS#226]
because the AUDIT tasks are shell, they do not run in check mode, which causes this line to fail due to missing dict object.

https://github.com/ansible-lockdown/RHEL9-CIS/blob/cf4376f1f7f0aaf48d28511ecc0d840bbe70a1e2/tasks/section_4/cis_4.1.4.x.yml#L26

**Comment by uk-bolly** [comment]
hi @karlg100 

Thank you for taking the time to raise this issue. I have added a fix to resolve this issue.
I will be raising the PR to get moved to devel last today.

Many thanks

uk-bolly

**Comment by uk-bolly** [comment]
hi @karlg100 

This issue and fix has been resolved and merged to both devel and main branches. I will therefore close this.

many thanks again for raising.

uk-bolly

**Comment by karlg100** [comment]
Thank you!
