### ISSUE TITLE
Merged Commit broke audit playbook

### ISSUE THREAD

**Issue by ckbaker10** [ansible-lockdown/RHEL9-CIS#227]
**Describe the Issue**

The playbook is supposed to use the outfile variable but has been replaced by a static string

https://github.com/ansible-lockdown/RHEL9-CIS/commit/dbbe8a9f333ab49223a16e0a736cec7c1bb2e27a#diff-750351722047e9b8b470c93a9f6401477262c3328bce086fcd68e74cb67c5792R38

**Control(s) Affected**
audit workflow

**Environment (please complete the following information):**

- branch being used: devel

**Comment by uk-bolly** [comment]
hi @ckbaker10 

Thank you for raising this issue, great spot. I have raised and fix and new branch. Hoping to get merged to devel later today.

Many thanks

uk-bolly

**Comment by uk-bolly** [comment]
hi @ckbaker10 

This fix has now been merged in both dvel and main branches. I will therefore close this issue.

many thanks

uk-bolly
