### ISSUE TITLE
In the latest release and develop branch the final audit output is broken

### ISSUE THREAD

**Issue by ckbaker10** [ansible-lockdown/RHEL9-CIS#229]
Release Commit:

https://github.com/ansible-lockdown/RHEL9-CIS/blob/151896e113ddaad98c596e3968051b4b0b81e8ed/tasks/main.yml#L218

https://github.com/ansible-lockdown/RHEL9-CIS/blob/151896e113ddaad98c596e3968051b4b0b81e8ed/tasks/post_remediation_audit.yml#L46

Dev Branch:

https://github.com/ansible-lockdown/RHEL9-CIS/blob/devel/tasks/main.yml#L218

https://github.com/ansible-lockdown/RHEL9-CIS/blob/devel/tasks/post_remediation_audit.yml#L44

The final audit message is broken in both since it refers to variable "audit_results" in the case of the release only "post_audit_summary" is registered.

For the dev branch post_audit_results is registered. 

In both cases the task breaks.

Sorry for not posting pull requests for these minor issues. I am currently very short on time.

**Comment by uk-bolly** [comment]
hi @ckbaker10 

Thanks for raising this issue. I have just checked. I have an open PR to fix the issues into devel which will be merged in main normally a couple of weeks later and a new release it cut. Branch=august_issues
Just validating which branches you are using. The new branch (open PR) does have expected outputs.

Let me know if there is something missing.

Full playbook including remediation
```
ok: [rocky9_bios] => {
    "msg": [
        "The pre remediation audit results are: Count: 661, Failed: 260, Skipped: 16, Duration: 28.471s",
        "The post remediation audit results are: Count: 661, Failed: 22, Skipped: 1, Duration: 34.093s",
        "Full breakdown can be found in /opt",
        ""
    ]
}
ok: [rocky9_efi] => {
    "msg": [
        "The pre remediation audit results are: Count: 661, Failed: 257, Skipped: 15, Duration: 28.133s",
        "The post remediation audit results are: Count: 661, Failed: 15, Skipped: 0, Duration: 33.943s",
        "Full breakdown can be found in /opt",
        ""
    ]
}
```

Audit Only run
```
ok: [rocky9_bios] => {
    "msg": [
        "The audit results are: Count: 661, Failed: 22, Skipped: 1, Duration: 33.581s",
        "",
        "Full breakdown can be found in /opt",
        ""
    ]
}
ok: [rocky9_efi] => {
    "msg": [
        "The audit results are: Count: 661, Failed: 15, Skipped: 0, Duration: 34.537s",
        "",
        "Full breakdown can be found in /opt",
        ""
    ]
}
```

audit_only documentation format
```
ok: [rocky9_bios] => {
    "msg": [
        "The audit results are: Count: 661, Failed: 22, Skipped: 1 Total Duration: 33.502s ",
        "",
        "Full breakdown can be found in /opt",
        ""
    ]
}
ok: [rocky9_efi] => {
    "msg": [
        "The audit results are: Count: 661, Failed: 15, Skipped: 0 Total Duration: 34.529s ",
        "",
        "Full breakdown can be found in /opt",
        ""
    ]
}
```

many thanks

uk-bolly

**Comment by uk-bolly** [comment]
hi @ckbaker10 

The mentioned branch has now been merged. Please let us know if this fixes your issue. If not if you could let us know the command you are running etc.

Many thanks

uk-bolly

**Comment by uk-bolly** [comment]
hi @ckbaker10 

as with previous issue this should now be resolved on both devel and main branches.

Many thanks

uk-bolly
