### ISSUE TITLE
many 5.2.X sections edit the sshd config file but do not call the restart handler for sshd

### ISSUE THREAD

**Issue by numericillustration** [ansible-lockdown/RHEL9-CIS#230]
**Describe the Issue**
Multiple items in section 5.2 are missing a notify to the sshd restart handler

**Expected Behavior**
Making changes to sshd's config file should restart sshd to make those changes active

**Actual Behavior**
changes are made to sshd'c config with no restart of sshd

**Control(s) Affected**
5.2.5
5.2.6
5.2.7
5.2.8
5.2.9
5.2.10
5.2.11
5.2.12
5.2.13

5.2.15
5.2.16
5.2.17
5.2.18
5.2.19
5.2.20

**Environment (please complete the following information):**

- branch being used: [e.g. devel] level 
- Ansible Version: [e.g. 2.10]  ansible [core 2.12.7]
- Host Python Version: [e.g. Python 3.7.6] 3.10.2
- Ansible Server Python Version: [e.g. Python 3.7.6] same
- Additional Details:

**Additional Notes**
I will PR in a fix for this sometime tonight

**Possible Solution**
add a notify to the existing sshd restart handler already used in other 5.2 sections,

**Comment by jLemmings** [comment]
Could we please have a release with this PR? Just wanted to do the same changes but @numericillustration has already done them.
