### ISSUE TITLE
4.2.1.5: Typo in Rsyslog rule

### ISSUE THREAD

**Issue by Arkhenys** [ansible-lockdown/RHEL9-CIS#232]
**Describe the Issue**

There is a typo during the /etc/rsyslog.conf edition.
Instead of adding 
`*.emerg                                                    :omusrmsg:*`

The following line is added:
` *.emrg                                                    :omusrmsg:*`

You can see it [here](https://github.com/ansible-lockdown/RHEL9-CIS/blob/main/tasks/section_4/cis_4.2.1.x.yml#L126)

**Expected Behavior**

No warning message should be displayed when running rsyslogd command.

**Actual Behavior**

Warning message encountered using rsyslogd: 
rsyslogd: unknown priority name "emrg"

**Environment (please complete the following information):**

- branch being used: main (but also appears on devel)
- Ansible Version: 2.16.2
- Host Python Version: 3.11.5
- Ansible Server Python Version: 3.11.5
- Additional Details: OS Oracle Linux 9

**Possible Solution**

Add the missing "e" to the rule.

**Comment by uk-bolly** [comment]
hi @Arkhenys 

Thank you again, this fix has now been merged to main and devel environments. I will now close this issue.

Many thanks

uk-bolly
