### ISSUE TITLE
Feature disparity between CIS-EL8 and EL9

### ISSUE THREAD

**Issue by Thulium-Drake** [ansible-lockdown/RHEL9-CIS#247]
**Describe the Issue**
In the RHEL8 version of this role, control 1.1.7.4 and 1.1.7.5 exist that enforce user- and group quota's on the mount for ```/home```.

In the RHEL9 version of the role, this is no longer the case and (in my case) running the role actively removes these mount options, leaving systems configured differently.

Is that intended by the CIS guidelines (and should I change my config)?

**Expected Behavior**
Both systems behave the same with regards of configuring mounts.

**Actual Behavior**
In my environment I am managing filesystem mounts with a role for both RHEL8 and RHEL9, but there's a idempotency issue right now :-)

**Control(s) Affected**
1.1.7.4 and 1.1.7.5 (if they exist in RHEL9)

**Environment (please complete the following information):**

- branch being used: master
- Ansible Version: 2.16
- Host Python Version: 3.12
- Ansible Server Python Version: 3.9.18
- Additional Details:

**Possible Solution**
If not mandatory, can we have a means of adding these mount options manually? :-)

**Comment by uk-bolly** [comment]
hi @Thulium-Drake 

Thanks as always fro your feedback. I am working on this currently hoping to have the PR raised asap.

Kindest regards

uk-bolly

**Comment by uk-bolly** [comment]
hi @Thulium-Drake 

Thank you again for this issue. The fix has been applied and is now in the main branch and release. I will close this issue, Please reopen if you feel this is not resolved.

Many thanks

uk-bolly
