### ISSUE TITLE
Write changes to /etc/ssh/sshd_config.d/55-CIS.conf instead of /etc/ssh/sshd_config

### ISSUE THREAD

**Issue by smatterchew** [ansible-lockdown/RHEL9-CIS#30]
## Feature Request or Enhancement

- Feature []
- Enhancement [X]

**Summary of Request**
RHEL 9 supports drop-in configuration files for sshd. Writing configuration changes to /etc/ssh/sshd_config prevents future upgrades writing a new version of the config file because it is no longer owned by the openssh-server package.  

**Describe alternatives you've considered**
I've configured sshd the same way this role is doing it.  The issue becomes the stability of the overall configuration when you have multiple roles adding/changing the contents of the file.  

**Suggested Code**
I would suggest you write any changes to /etc/ssh/sshd_confi.d/55-CIS.conf instead of the file owned by the openssh-server.

**Comment by smatterchew** [comment]
Another option would be to replace the hard-coded path to the `/etc/sshd_config` file with a var like `rhel9_cis_sshd_config_file` and let me override the path when I call the role.  Task names would likely have to be updated as well.  I've never forked someone else's repo to provide update via PR before, but I can give it a shot if that is what you prefer.

**Comment by uk-bolly** [comment]
hi @smatterchew 

Thank you for raising this issue. This is very likely to be included in the RHEL9-cis Benchmark when it gets released. I have seen part of the STIG which is often similar and they are adopting this new option.
This may work well as a new template file.
We will need to align all the audit checks as well. Hopefully will get a chance to look into this soon.
If you wanted to fork it and update it in your own branch and create PR happy to go through this with you. We do ask that each commit you make is signed-off-by and gpg signed.

kindest regards

uk-bolly
