### ISSUE TITLE
rhel9cis_rule_1_1_3' is undefined

### ISSUE THREAD

**Issue by I-am-MoS** [ansible-lockdown/RHEL9-CIS#40]
**Describe the Issue**
If you set rhel9cis_tmp_svc: true
True = tmp.mount service
False = /etc/ftab
Default setting was: false

Code fails with:
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.errors.AnsibleUndefinedVariable: 'rhel9cis_rule_1_1_3' is undefined
fatal: [rhel9-test]: FAILED! => {
    "changed": false
}

MSG:

AnsibleUndefinedVariable: 'rhel9cis_rule_1_1_3' is undefined

**Expected Behavior**
Not fail

**Actual Behavior**
Fails

**Additional Notes**
Looks like issue is in tmp.mount.j2 file
Options=mode=1777,strictatime,{% if rhel9cis_rule_1_1_3 %}nodev,{% endif %}{% if rhel9cis_rule_1_1_4 %}nosuid,{% endif %}{% if rhel9cis_rule_1_1_5 %}noexec{% endif %}

There is no variable named  just 1_1_3, 1_1_4, 1_1_5 
Looks like these also were mistypes for /var not /tmp

**Possible Solution**
Var ids should be 
1_1_4_4  for nodev
1_1_4_3   for nosuid
1_1_4_2   for noexec

**Comment by I-am-MoS** [comment]
Related to above, I didnt have a chance to test changes fully , I only saw it get past the one section. 

Now I see:

RUNNING HANDLER [nix-cis-rhel9-vendor : Systemd restart tmp.mount] *************
fatal: [goldenImageTest-sucherm-rhel9]: FAILED! => {
    "changed": false
}

MSG:

value of state must be one of: reloaded, restarted, started, stopped, got: Reloaded

In the handler/main.yml file:

- name: Systemd restart tmp.mount
  ansible.builtin.systemd:
      name: tmp.mount
      daemon_Reload: true
      enabled: true
      masked: false
      state: Reloaded

Just make Reloaded, lower case to reloaded.

**Comment by I-am-MoS** [comment]
Another in handlers issue with caps, 

- name: Systemd restart tmp.mount
  ansible.builtin.systemd:
      name: tmp.mount
      daemon_Reload: true
      enabled: true
      masked: false
      state: reloaded

daemon_Reload 
to
daemon_reload

**Comment by uk-bolly** [comment]
hi @I-am-MoS 

Thank you again for the feedback and highlighting these issues. I have now raised a PR to get these addressed asap.

Many thanks

uk-bolly
