### ISSUE TITLE
Wrong parameters set for pam_pwhistory.so

### ISSUE THREAD

**Issue by mj84** [ansible-lockdown/RHEL9-CIS#53]
**Describe the Issue**
pam_pwhistory.so currently gets passed the unsupported parameters `try_first_pass` and `local_users_only`. This seems to be a copy & paste error from pam_pwquality where these parameters are supported.

**Expected Behavior**
pam_pwhistory.so should only receive supported parameters.

**Actual Behavior**
The following line will be written to `/etc/pam.d/system-auth`:
`password    requisite     pam_pwhistory.so try_first_pass local_users_only enforce_for_root retry=3 remember={{ rhel9cis_pam_faillock.remember }}`

This causes password changes to be rejected and the following message is logged:
`pam_pwhistory(passwd:chauthtok): pam_pwhistory: unknown option: local_users_only`

**Control(s) Affected**
5.5.3 | PATCH | Ensure password reuse is limited

**Environment (please complete the following information):**

- branch being used: [e.g. devel]
- Ansible Version: [e.g. 2.11]
- Host Python Version: [e.g. Python 3.9.14]
- Ansible Server Python Version: [e.g. Python 3.6.8]
- Additional Details:

**Additional Notes**
Will send a PR once I've tested everything.

**Possible Solution**
Remove the 2 unsupported parameters

**Comment by mj84** [comment]
Mixed up the pam modules, updated the original description

**Comment by uk-bolly** [comment]
hi @mj84 

Good catch, thanks for taking the time to raise this. I have added the fix (although that error does appear on a clean fresh server too). This also highlighted another issues which i have no addressed also.

Many thanks

uk-bolly

**Comment by frederickw082922** [comment]
Thank you @mj84 for submitting the Issue!
