### ISSUE TITLE
Default GRUB password

### ISSUE THREAD

**Issue by ambommer** [ansible-lockdown/RHEL9-CIS#70]
What's the default grub password? in defaults/main.yaml. I see it uses the rhel9cis_bootloader_password_hash and not the rhel9cis_bootloader_password, so I am unable to figure out what it is.

**Comment by uk-bolly** [comment]
hi @ambommer 

Thank you for the enquiry, I will add a comment to say you should change this to be what you wish it to be and create another check to ensure that it has been changed from the default.
Ideally everyone should be understanding what each component does and ensure changing any values to what you wish them to be. I would strongly advise to always read and test before running anything you have not written yourself.

I believe the password is 'vagrant' as we use in our testing.

I hope that helps?

Many thanks

uk-bolly
