### ISSUE TITLE
Call ansible.builtin.mount doesn't work 

### ISSUE THREAD

**Issue by agbrowne** [ansible-lockdown/RHEL9-CIS#79]
**Describe the Issue**
The file RHEL9-CIS/tasks/section_1/cis_1.1.2.x.yml has a call to 'ansible.builtin.mount' on line 29. This always fails with Ansible version 2.14.2.

**Expected Behavior**
Expected the RHEL9-CIS to run without issue

**Actual Behavior**
Ansible cannot find 'ansible.builtin.mount' and fails.

**Control(s) Affected**
Section 1.1.2.x

**Environment (please complete the following information):**

- branch being used: main
- Ansible Version: ansible [core 2.14.2]
- Host Python Version: Python 3.9.16
- Ansible Server Python Version: Python 3.11.2 (as reported by 'ansible --version')
- Additional Details: 
Both host and ansible server are running AlmaLinux 9.2
Changing 'ansible.builtin.mount' to 'ansible.posix.mount' fixes the issue.

**Additional Notes**
Anything additional goes here

**Possible Solution**
Change the reference to 'ansible.builtin.mount' to 'ansible.posix.mount' in RHEL9-CIS/tasks/section_1/cis_1.1.2.x.yml

**Comment by uk-bolly** [comment]
hi @agbrowne 

Thank you for taking the time to raise this Issue, it is with feedback we are able to improve the project. This particular issue has been addressed in the devel branch already.
If you could test that and see if this is now resolved for you.
We will be adding a couple more features to devel before the next merge.

I hope this helps.

uk-bolly

**Comment by agbrowne** [comment]
Thanks
I subsequently found out that I wasn't in fact using the main branch. Sometimes 'git' is not my friend!
I have sorted it out now and the main branch appears to reflect the change to 'ansible.posix.mount'. I'm testing things now.

**Comment by agbrowne** [comment]
This problem is now fixed in the main branch
