### ISSUE TITLE
Journald issue - skipped

### ISSUE THREAD

**Issue by snoopyx21** [ansible-lockdown/RHEL9-CIS#91]
**Describe the Issue**
The tasks are skipped even if systemd-journald is enabled & started and that the variables 4_2_2_2 are set to true.

**Expected Behavior**
All 4.2.2.2.x tasks should run normally.
The variable are set to true.

**Actual Behavior**
All 4.2.2.2.x tasks are skipped.

**Control(s) Affected**
4.2.2.2.X

**Environment (please complete the following information):**

- branch being used: [main]
- Ansible Version: [2.14.2]
- Host Python Version: [3.11]
- Ansible Server Python Version: [3.11]

**Additional Notes**

![RHEL9_CIS_journald_true](https://github.com/ansible-lockdown/RHEL9-CIS/assets/116892320/3a0397dc-8904-445f-b1ce-158f2790bd98)
![RHEL9_CIS_skipped_ansible](https://github.com/ansible-lockdown/RHEL9-CIS/assets/116892320/3c91ff4a-6df0-475a-993c-14c5da8c2466)
![RHEL9_CIS_journald_service](https://github.com/ansible-lockdown/RHEL9-CIS/assets/116892320/09d6ddb1-941c-4a5f-bd30-0b7b6d6c616a)

**Comment by uk-bolly** [comment]
hi @snoopyx21 

Thank you for taking the time to raise this issue and for the information provided. I have taken q quick look. There is a setting that tells ansible which syslog service you are using.
Have you set the following to be journald?

```
## Preferred method of logging
## Whether rsyslog or journald preferred method for local logging
## Affects rsyslog cis 4.2.1.3 and journald cis 4.2.2.5
rhel9cis_syslog: rsyslog
```

many thanks

uk-bolly

**Comment by snoopyx21** [comment]
hi @uk-bolly,

thanks for your answer !
i set it up to rsyslog, it has to be journald or it is skipped ?

best regards;
snoop

**Comment by uk-bolly** [comment]
Hi @snoopyx21 

Thats correct CIS pushes to one or the other and even when you chose rsyslog that makes changes to journald to ensure that sends to rsyslog and vice versa if chosen.
So it is expected to skip if the syslog service is set to rsyslog.

many thanks

uk-bolly

**Comment by uk-bolly** [comment]
hi @snoopyx21 

Hopefully that is working as expected for you now? Please lt eus know if there is anything missing.

many thanks

uk-bolly

**Comment by snoopyx21** [comment]
hi @uk-bolly 

it is working as expected to me, I am sorry to have open that as an issue!

Best regards,
snoopy
